# Generated by Django 3.1.4 on 2020-12-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20201210_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='text',
        ),
    ]
